### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by EficodeRjpalt** [EficodeDemoOrg/copilot-fullstack-demo#3]
# Dark Mode Feature Specification

## User Story

As a user, I want to be able to toggle between a light and dark theme for the application, so that I can choose the mode that is most comfortable for my eyes and environment, and my preference should be remembered across sessions.

### 1. Theme Switching Mechanism

*   **Toggle Control:**
    *   Implement a toggle button or switch.
    *   Location: Place it in a clearly visible and accessible part of the `App.tsx` component, for instance, in the header area.
    *   Labeling: Use an icon (e.g., sun/moon) or simple text (e.g., "Toggle Theme") for the button.
*   **State Management:**
    *   Use React's `useState` hook in `App.tsx` to manage the current theme state (e.g., `isDarkMode: boolean`).
    *   Use React's `useEffect` hook to:
        *   On initial application load: Read the theme preference from `localStorage` (e.g., under a key like `app-theme-preference`). If a preference exists (e.g., 'dark' or 'light'), apply it. If not, default to 'light' theme.
        *   On theme state change: Update `localStorage` with the new preference and apply/remove a specific CSS class (e.g., `dark-mode`) to the `document.body` or the main application container `div`.
*   **Default Theme:** Light theme.

### 2. Styling

*   **CSS Variables:**
    *   Define all theme-related colors using CSS variables in a global stylesheet (e.g., `packages/frontend/src/index.css` or `packages/frontend/src/App.css`).
    *   Minimum required variables:
        *   `--background-color`
        *   `--text-color`
        *   `--primary-accent-color` (e.g., for buttons, interactive elements)
        *   `--secondary-accent-color` (e.g., for borders, less prominent elements)
        *   `--table-header-background`
        *   `--table-cell-background`
        *   `--table-border-color`
        *   `--input-background-color`
        *   `--input-text-color`
        *   `--input-border-color`
        *   `--button-text-color`
*   **Theme Definitions:**
    *   In the global stylesheet, define the default (light theme) values for the CSS variables within the `:root` selector.
    *   Define the dark theme overrides for these variables under a class selector (e.g., `body.dark-mode` or `.app-container.dark-mode`).
    ```css
    /* Example for index.css or App.css */
    :root {
      --background-color: #f8f9fa;
      --text-color: #212529;
      --primary-accent-color: #007bff;
      --button-text-color: #ffffff;
      /* ... other light theme variables ... */
    }

    body.dark-mode { /* Or your main app container if body is not directly controlled by React app */
      --background-color: #212529;
      --text-color: #f8f9fa;
      --primary-accent-color: #0d6efd; /* Adjust as needed for dark theme */
      --button-text-color: #ffffff;
      /* ... other dark theme variables ... */
    }

    /* Apply base styles */
    body { /* Or your main app container */
      background-color: var(--background-color);
      color: var(--text-color);
      transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out;
    }
    ```
*   **Component Styling:**
    *   Review and update existing components (`App.tsx`, `ParentSelector.tsx`, `TraitLegends.tsx`, `TraitResultsTable.tsx`, and any other relevant UI components) to ensure all color-related styles use the defined CSS variables. Remove or refactor inline styles or hardcoded color values.

### 3. Testing

*   **Unit/Component Tests (e.g., in `packages/frontend/src/App.test.tsx`):**
    *   Verify the theme toggle button/switch renders correctly.
    *   Mock `localStorage`.
    *   Test that clicking the toggle:
        *   Updates the theme state in the component.
        *   Calls `localStorage.setItem` with the correct theme preference.
        *   Applies/removes the `dark-mode` class to the designated HTML element (e.g., `document.body` or main app `div`).
    *   Test initial theme setting:
        *   Verify the correct theme is applied based on `localStorage` value on component mount.
        *   Verify the light theme is applied by default if no preference is found in `localStorage`.
*   **E2E Tests (new file, e.g., `packages/frontend/cypress/e2e/core/theme-switching.cy.ts`):**
    *   Test 1: Default theme.
        *   Visit the page.
        *   Assert that the default (light) theme is applied (e.g., check `background-color` of `body` or main container).
        *   Assert `localStorage` does not initially contain the theme preference or it's set to 'light'.
    *   Test 2: Toggle to Dark Mode.
        *   Click the theme toggle.
        *   Assert that the dark theme is applied (e.g., check `background-color`).
        *   Assert `localStorage` now stores 'dark' as the preference.
    *   Test 3: Persistence of Dark Mode.
        *   With dark mode active (from Test 2 or set directly), reload the page.
        *   Assert that the dark theme is still applied.
        *   Assert `localStorage` still stores 'dark'.
    *   Test 4: Toggle back to Light Mode & Persistence.
        *   Click the theme toggle again (to switch from dark to light).
        *   Assert that the light theme is applied.
        *   Assert `localStorage` now stores 'light'.
        *   Reload the page.
        *   Assert that the light theme is still applied.

### 4. Files to be Modified (Anticipated)

*   `packages/frontend/src/App.tsx` (for toggle UI, state logic, effect for localStorage and class toggling)
*   `packages/frontend/src/index.css` or `packages/frontend/src/App.css` (for CSS variable definitions and theme styles)
*   CSS/style files for `ParentSelector.tsx`, `TraitLegends.tsx`, `TraitResultsTable.tsx` if they have hardcoded colors that need to be updated to use CSS variables.
*   `packages/frontend/src/App.test.tsx` (for new unit tests)
*   New E2E test file: `packages/frontend/cypress/e2e/core/theme-switching.cy.ts`

### 5. Acceptance Criteria

*   A theme toggle control is present and functional in the UI.
*   Clicking the toggle switches the application's visual theme between light and dark.
*   The selected theme (light/dark) persists across page reloads and browser sessions.
*   The default theme is light if no user preference is stored.
*   All major UI elements (text, backgrounds, buttons, tables, inputs) correctly adapt to the selected theme.
*   The implementation includes new unit tests for the theme switching logic.
*   The implementation includes new E2E tests covering theme toggling and persistence.
*   All existing tests (unit and E2E) continue to pass.
*   The code adheres to project linting and formatting standards, and the application builds without errors.
